#!/usr/bin/env bash
set -euo pipefail

EXPECTED_ENV="${1:-}"
RUNTIME_ENV="${2:-/opt/quiz/api/.env}"
BACKUP_ROOT="${3:-/opt/quiz/backups/config}"
STAMP="${4:-$(date +%Y%m%d_%H%M%S)}"

[[ "$EXPECTED_ENV" == "test" || "$EXPECTED_ENV" == "prod" ]] || {
  echo "expected environment must be test or prod" >&2
  exit 2
}
[[ -f "$RUNTIME_ENV" ]] || {
  echo "runtime env not found: $RUNTIME_ENV" >&2
  exit 2
}

MERGED_FILE="$(mktemp)"
STATE_FILE="$(mktemp)"
cleanup() {
  rm -f "$MERGED_FILE" "$STATE_FILE"
}
trap cleanup EXIT
chmod 600 "$MERGED_FILE" "$STATE_FILE"

# 访问去重密钥仅在缺失时生成；校验与合并过程不输出密钥值。
node - "$EXPECTED_ENV" "$RUNTIME_ENV" "$MERGED_FILE" "$STATE_FILE" <<'NODE'
const crypto = require('crypto')
const fs = require('fs')

const expectedEnv = process.argv[2]
const runtimeFile = process.argv[3]
const mergedFile = process.argv[4]
const stateFile = process.argv[5]
const runtimeText = fs.readFileSync(runtimeFile, 'utf8')

function entries(text) {
  const result = new Map()
  for (const line of text.split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=(.*)$/)
    if (match) result.set(match[1], match[2].trim())
  }
  return result
}

function unquote(value) {
  if (
    (value.startsWith('"') && value.endsWith('"'))
    || (value.startsWith("'") && value.endsWith("'"))
  ) {
    return value.slice(1, -1)
  }
  return value
}

const runtimeEntries = entries(runtimeText)
if (unquote(runtimeEntries.get('API_RUNTIME_ENV') || '') !== expectedEnv) {
  console.error('runtime environment guard failed')
  process.exit(49)
}

const existingSecret = unquote(runtimeEntries.get('VISITOR_IP_HASH_SECRET') || '')
if (existingSecret.length >= 64) {
  fs.writeFileSync(stateFile, 'unchanged', { encoding: 'utf8', mode: 0o600 })
  process.exit(0)
}

const retainedLines = runtimeText.split(/\r?\n/).filter((line) => {
  const match = line.match(/^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=/)
  return !match || match[1] !== 'VISITOR_IP_HASH_SECRET'
})
while (retainedLines.length && retainedLines.at(-1) === '') retainedLines.pop()
retainedLines.push(
  '',
  `# Visitor analytics secret generated by quiztestdemo-deploy (${new Date().toISOString()})`,
  `VISITOR_IP_HASH_SECRET=${crypto.randomBytes(64).toString('hex')}`,
  '',
)
fs.writeFileSync(mergedFile, retainedLines.join('\n'), { encoding: 'utf8', mode: 0o600 })
fs.writeFileSync(stateFile, 'merged', { encoding: 'utf8', mode: 0o600 })
NODE

if [[ "$(cat "$STATE_FILE")" == "unchanged" ]]; then
  echo "VISITOR_IP_HASH_SECRET is already configured; no runtime change made."
  exit 0
fi

mkdir -p "$BACKUP_ROOT"
BACKUP_FILE="$BACKUP_ROOT/runtime-env-before-visitor-config-$STAMP.tar.gz"
tar -czf "$BACKUP_FILE" -C "$(dirname "$RUNTIME_ENV")" "$(basename "$RUNTIME_ENV")"
chmod 600 "$BACKUP_FILE"
install -m 600 "$MERGED_FILE" "$RUNTIME_ENV"

echo "VISITOR_IP_HASH_SECRET generated and merged without printing its value."
echo "Runtime config backup: $BACKUP_FILE"
