export const EMAIL_CODE_PURPOSE = {
  REGISTER: 'REGISTER',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
} as const

export type EmailCodePurpose = (typeof EMAIL_CODE_PURPOSE)[keyof typeof EMAIL_CODE_PURPOSE]

export const AUTH_SESSION_EXPIRED_MESSAGE = '您已失去登录状态，请重新登录！'

export const AUTH_ERROR = {
  INVALID_INPUT: 'AUTH_INVALID_INPUT',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  EMAIL_IN_USE: 'AUTH_EMAIL_IN_USE',
  USERNAME_IN_USE: 'AUTH_USERNAME_IN_USE',
  EMAIL_CODE_INVALID: 'AUTH_EMAIL_CODE_INVALID',
  EMAIL_CODE_EXPIRED: 'AUTH_EMAIL_CODE_EXPIRED',
  EMAIL_CODE_ATTEMPTS_EXCEEDED: 'AUTH_EMAIL_CODE_ATTEMPTS_EXCEEDED',
  EMAIL_CODE_TOO_FREQUENT: 'AUTH_EMAIL_CODE_TOO_FREQUENT',
  EMAIL_SERVICE_UNAVAILABLE: 'AUTH_EMAIL_SERVICE_UNAVAILABLE',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  CURRENT_PASSWORD_INVALID: 'AUTH_CURRENT_PASSWORD_INVALID',
  PASSWORD_UNCHANGED: 'AUTH_PASSWORD_UNCHANGED',
  FORBIDDEN: 'AUTH_FORBIDDEN',
  RATE_LIMITED: 'AUTH_RATE_LIMITED',
} as const
