// 认证错误、邮箱验证码用途及独立账号状态的统一定义。
export const EMAIL_CODE_PURPOSE = {
  REGISTER: 'REGISTER',
  RESET_PASSWORD: 'RESET_PASSWORD',
  CHANGE_EMAIL: 'CHANGE_EMAIL',
} as const

export type EmailCodePurpose = (typeof EMAIL_CODE_PURPOSE)[keyof typeof EMAIL_CODE_PURPOSE]

export const AUTH_SESSION_EXPIRED_MESSAGE = '您已失去登录状态，请重新登录！'
export const AUTH_MAX_ACTIVE_IPS = 2
export const ACCOUNT_STATUS = { ACTIVE: 'active', BANNED: 'banned' } as const
export const AUTH_ACCOUNT_BANNED_MESSAGE = '该账号已被暂停使用。如需申请恢复，请联系客服。'

export const AUTH_ERROR = {
  REGISTRATION_IP_FREQUENT: 'AUTH_REGISTRATION_IP_FREQUENT',
  REGISTRATION_IP_DAILY: 'AUTH_REGISTRATION_IP_DAILY',
  REGISTRATION_BROWSER_FREQUENT: 'AUTH_REGISTRATION_BROWSER_FREQUENT',
  REGISTRATION_COOKIE_REQUIRED: 'AUTH_REGISTRATION_COOKIE_REQUIRED',
  REGISTRATION_RESTRICTED: 'AUTH_REGISTRATION_RESTRICTED',
  ACCOUNT_BANNED: 'AUTH_ACCOUNT_BANNED',
  INVALID_INPUT: 'AUTH_INVALID_INPUT',
  INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  EMAIL_IN_USE: 'AUTH_EMAIL_IN_USE',
  USERNAME_IN_USE: 'AUTH_USERNAME_IN_USE',
  EMAIL_CODE_INVALID: 'AUTH_EMAIL_CODE_INVALID',
  EMAIL_CODE_EXPIRED: 'AUTH_EMAIL_CODE_EXPIRED',
  EMAIL_CODE_ATTEMPTS_EXCEEDED: 'AUTH_EMAIL_CODE_ATTEMPTS_EXCEEDED',
  EMAIL_CODE_TOO_FREQUENT: 'AUTH_EMAIL_CODE_TOO_FREQUENT',
  EMAIL_SERVICE_UNAVAILABLE: 'AUTH_EMAIL_SERVICE_UNAVAILABLE',
  SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  CURRENT_PASSWORD_INVALID: 'AUTH_CURRENT_PASSWORD_INVALID',
  PASSWORD_UNCHANGED: 'AUTH_PASSWORD_UNCHANGED',
  FORBIDDEN: 'AUTH_FORBIDDEN',
  RATE_LIMITED: 'AUTH_RATE_LIMITED',
} as const
